# -*- coding: utf-8 -*-
"""HW4_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qGCmtrlsnpIO_ncGFfeTGh3VKmHz980d
"""

import numpy as np
import cv2
from numpy import linalg as LA

t1 = ('a', 'b',)
t2 = ('c',)
t3 = t1 + t2
print(f't1+t2 = {t3}')

n = int(input('숫자입력:'))
A = np.zeros((n,n))

for i in range(n):
    for j in range(n):
        A[i,j] = n*i+j
print(A)
B=A.reshape(-1, )

frame=cv2.imread('/content/lena.png', cv2.COLOR_BGR2RGB)
frame = frame/255

print("lena shape:", frame.shape)

frame2 = np.expand_dims(frame, 0)

frame3 = frame2.transpose(0, 3, 1, 2)

c = np.array([1,2,3,4])
print(c)
print(c + c)

b = ([1,2,3,4])
print(b+b)

a = np.array([[1,2],[3,4]])
print(a)

a = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(a)

a = np.array([1,2,3,4])
b = np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

c = np.array([[1,2,3],[-1,1,4]])
print(LA.norm(c, axis=0))
print(LA.norm(c, axis=1))
print(LA.norm(c, ord=1, axis=1))
print(LA.norm(c, ord=2, axis=1))

A = np.array([[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n = 4
for i in range(0, n):
  val = 0.0
  for j in range(0, n):
    val += A[i,j]*x[j]
  b[i] = val
print("calculate=", b)

b = np.dot(A, x)
print("dot=", b)

b = np.matmul(A, x)
print("matmul=", b)

b = A@x
print("A@=", b)

b = A*x
print("A*x=", b)

A = np.array([[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]])
x = np.array([15,19,26,44])

print("det=", np.linalg.det(A))

x = np.linalg.solve(A, b)
print("solver=", x)

x = np.dot(np.linalg.inv(A), b)
print("inverse1=", x)

tmp_b=np.dot(A.T, x)
tmp_T=np.dot(A.T, A)
tmp_inv=np.linalg.inv(np.dot(A.T, A))
x=np.dot(tmp_inv, tmp_b)
print("inverse2=", x)